(deftheme my-color)

(custom-theme-set-faces
 'my-color
 ;; TODO: company?
 '(compilation-mode-line-fail ((t (:weight bold :inherit error))))
 '(completions-common-part ((t (:foreground "#7C7C7C"))))
 '(completions-first-difference ((t (:foreground "yellow"))))
 '(cursor ((t (:background "white"))))
 '(default ((t (:background "black" :foreground "#f6f3e8"))))
 '(diff-added ((t (:foreground "SeaGreen1"))))
 '(diff-changed ((t (:foreground "blue3"))))
 '(diff-file-header ((t (:foreground "cyan"))))
 '(diff-header ((t (:foreground "dark cyan"))))
 '(diff-refine-added ((t (:background "midnight blue"))))
 '(diff-refine-changed ((t (:background "midnight blue"))))
 '(diff-refine-removed ((t (:background "midnight blue"))))
 '(diff-removed ((t (:foreground "indian red"))))
 '(error ((t (:foreground "#FF6C60"))))
 '(font-lock-builtin-face ((t (:foreground "#DFEFFE"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#7C7C7C"))))
 '(font-lock-constant-face ((t (:foreground "#99CC99"))))
 '(font-lock-doc-face ((t (:foreground "#ffccff"))))
 '(font-lock-function-name-face ((t (:foreground "#FFD2A7"))))
 '(font-lock-keyword-face ((t (:foreground "#DFEFFE"))))
 '(font-lock-preprocessor-face ((t (:foreground "#6699CC"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#B18A3D"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#B18A3D"))))
 '(font-lock-string-face ((t (:foreground "#B6FF7A"))))
 '(font-lock-type-face ((t (:foreground "#FFFFB6"))))
 '(font-lock-variable-name-face ((t (:foreground "#C6C5FE"))))
 '(font-lock-warning-face ((t (:foreground "#FF6C60"))))
 '(highlight ((t (:inherit 'lazy-highlight))))
 '(hl-line ((t (:background "#121212"))))
 '(isearch ((t (:background "#2F2F00" :foreground "white"))))
 '(lazy-highlight ((t (:background "#412b14" :foreground "white"))))
 '(mode-line ((t (:background "gray15" :foreground "light blue"))))
 '(mode-line-buffer-id ((t (:foreground "red4"))))
 '(mode-line-inactive ((t (:background "#a9a9a9" :foreground "blue4"))))
 '(region ((t :background "#262D51")))
 '(success ((t (:weight bold :foreground "#A8FF60"))))
 '(whitespace-empty ((t (:foreground "#303030"))))
 '(whitespace-hspace ((t (:foreground "#303030"))))
 '(whitespace-newline ((t (:foreground "#303030"))))
 '(whitespace-indentation ((t (:foreground "#303030"))))
 '(whitespace-space ((t (:foreground "#303030"))))
 '(whitespace-space-after-tab ((t (:foreground "#303030"))))
 '(whitespace-space-before-tab ((t (:foreground "#303030"))))
 '(whitespace-tab ((t (:foreground "#303030"))))
 '(whitespace-trailing ((t (:foreground "red2")))))

(provide-theme 'my-color)
;;; my-color-theme.el ends here
